receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: otelcol:4317

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

extensions:
  # health_check:
  # pprof:
  # zpages:

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    # metrics:
      # receivers: [otlp]
      # processors: [batch]
      # exporters: [jaeger]
    # logs:
      # receivers: [otlp]
      # processors: [batch]
      # exporters: [jaeger]
